{% set version = "1.6.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-hypetools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/HYPEtools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/HYPEtools/HYPEtools_{{ version }}.tar.gz
  sha256: 222907338115abb2fcaef96a2693a2eb8517b3a211f8eba59b456dec34535b0b

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-clipr
    - r-data.table >=1.9.8
    - r-dplyr
    - r-ggplot2
    - r-ggpubr
    - r-ggrepel
    - r-ggspatial
    - r-hydrogof
    - r-ncdf4
    - r-patchwork
    - r-pbapply
    - r-purrr
    - r-rlang
    - r-sf
    - r-stringr
    - r-tidyr
    - r-tidyselect
  run:
    - r-base
    - r-clipr
    - r-data.table >=1.9.8
    - r-dplyr
    - r-ggplot2
    - r-ggpubr
    - r-ggrepel
    - r-ggspatial
    - r-hydrogof
    - r-ncdf4
    - r-patchwork
    - r-pbapply
    - r-purrr
    - r-rlang
    - r-sf
    - r-stringr
    - r-tidyr
    - r-tidyselect

test:
  commands:
    - $R -e "library('HYPEtools')"           # [not win]
    - "\"%R%\" -e \"library('HYPEtools')\""  # [win]

about:
  home: https://hypeweb.smhi.se/
  dev_url: https://github.com/rcapell/HYPEtools
  license: LGPL-3.0-only
  summary: 'Work with model files (setup, input, output) from the hydrological catchment model HYPE: Streamlined file import and export, standard evaluation plot routines, diverse post-processing and aggregation routines for hydrological model analysis.'
  license_family: LGPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - c-brendel
